export const API_URL = "https://jsonfakery.com/jobs";

export const categories = [
  "Back-end Developer",
  "Data Scientist",
  "Data Administrator",
  "DevOps Engineer",
  "Front-end Developer",
  "Full-stack Developer",
  "Mobile App Developer",
  "QA Engineer",
  "Security Engineer",
  "UI/UX Designer",
];

export const featuredJobs = [
  {
    id: "fa57f753-7075-419b-ab1f-416f927a5817",
    title: "Bartender Helper",
    description:
      "Deserunt et dolorum et odit. Et minima aspernatur omnis facilis voluptatibus illum. Praesentium explicabo ut quia aut consequatur nostrum.",
    company: "Bogan Ltd",
    location: "Borongan, Slovenia",
    salary_from: 69639,
    salary_to: 97678,
    employment_type: "Freelance Developer",
    application_deadline: "Wed, 05/07/1980",
    qualifications:
      '["Expert in Java","Master of TypeScript","3+ years in Angular","Expert in Docker"]',
    contact: "233-577-406",
    job_category: "Front-end Developer",
    is_remote_work: 0,
    number_of_opening: 5,
    created_at: "Sun, 10/15/2023",
    updated_at: "Sun, 10/15/2023",
    image: "../assets/office.avif",
  },
  {
    id: "d1f4651a-aff6-45cd-ab88-ddd3fd660282",
    title: "Fishing OR Forestry Supervisor",
    description:
      "Quos vero totam non tempora et sunt et. Et debitis dolore eaque magni et. Harum eum magnam ex sint consequatur voluptatibus totam.",
    company: "Kunde-Herman",
    location: "Butuan, Iran",
    salary_from: 65447,
    salary_to: 113981,
    employment_type: "Co-founder/Technical Partner",
    application_deadline: "Tue, 02/28/1978",
    qualifications:
      '["3 years in Node.js","Proficient in MongoDB","Skilled in GraphQL","2 years in Vue.js"]',
    contact: "080-552-063",
    job_category: "QA Engineer",
    is_remote_work: 1,
    number_of_opening: 9,
    created_at: "Sun, 10/15/2023",
    updated_at: "Sun, 10/15/2023",
    image: "../assets/office.avif",
  },
  {
    id: "8a0efa45-f855-4124-88bb-9fa6bbcd4739",
    title: "Computer Security Specialist",
    description:
      "Sint cumque optio pariatur neque sint provident distinctio. Qui temporibus exercitationem voluptate error. Et nisi nulla nemo nihil enim ullam a quae. Enim mollitia tempora minima ut.",
    company: "Bernhard-Abshire",
    location: "San Jose del Monte, Andorra",
    salary_from: 67029,
    salary_to: 85223,
    employment_type: "Contract Developer",
    application_deadline: "Thu, 06/13/2013",
    qualifications:
      '["Expert in JavaScript","Skilled in React","3 years in Node.js","3+ years in Angular"]',
    contact: "046-407-366",
    job_category: "Front-end Developer",
    is_remote_work: 1,
    number_of_opening: 7,
    created_at: "Sun, 10/15/2023",
    updated_at: "Sun, 10/15/2023",
    image: "../assets/office.avif",
  },
  {
    id: "1f62b3e7-628f-4b99-9b35-806cea1f1019",
    title: "Stationary Engineer OR Boiler Operator",
    description:
      "Esse repudiandae eos ipsum fugit rerum. Ut non tempora eos sit magni reprehenderit. Voluptas ut quia quaerat deleniti. Provident voluptatum commodi voluptas illo.",
    company: "Stanton-O'Hara",
    location: "Gapan, Comoros",
    salary_from: 61515,
    salary_to: 109264,
    employment_type: "Co-founder/Technical Partner",
    application_deadline: "Sat, 04/17/1971",
    qualifications:
      '["Expert in JavaScript","Proficient in Kotlin","Solid understanding of AWS","Proficient in MongoDB"]',
    contact: "969-860-302",
    job_category: "Full-stack Developer",
    is_remote_work: 1,
    number_of_opening: 10,
    created_at: "Sun, 10/15/2023",
    updated_at: "Sun, 10/15/2023",
    image: "../assets/office.avif",
  },
  {
    id: "2c03c800-1e1e-4097-adeb-66f87f428271",
    title: "Nuclear Monitoring Technician",
    description:
      "Optio ipsam est expedita aut aut eum cum. Impedit repellat ut deserunt magnam quia sint enim. Est nihil impedit qui ipsam.",
    company: "Kuvalis, Okuneva and Wintheiser",
    location: "Kabankalan, Ghana",
    salary_from: 67210,
    salary_to: 112078,
    employment_type: "Contract Developer",
    application_deadline: "Sun, 05/08/2016",
    qualifications:
      '["2 years of Git experience","3 years in Node.js","Master of TypeScript","2+ years in Ruby"]',
    contact: "147-801-736",
    job_category: "Mobile App Developer",
    is_remote_work: 0,
    number_of_opening: 7,
    created_at: "Sun, 10/15/2023",
    updated_at: "Sun, 10/15/2023",
    image: "../assets/office.avif",
  },
  {
    id: "aaa3f210-d28b-4059-829d-9100739962b3",
    title: "Fraud Investigator",
    description:
      "Fugiat nihil tempore autem. Nostrum laborum aliquam excepturi repellat. Neque tempora quia temporibus velit enim nihil eaque.",
    company: "Denesik, Cummerata and Hettinger",
    location: "Mati, Albania",
    salary_from: 57178,
    salary_to: 113311,
    employment_type: "Full-time Developer",
    application_deadline: "Fri, 06/25/1993",
    qualifications:
      '["3+ years in Python","Proficient in SQL","Solid understanding of AWS","Proficient in MongoDB"]',
    contact: "936-419-430",
    job_category: "Mobile App Developer",
    is_remote_work: 1,
    number_of_opening: 2,
    created_at: "Sun, 10/15/2023",
    updated_at: "Sun, 10/15/2023",
    image: "../assets/office.avif",
  },
  {
    id: "71f678c0-6a5e-45bb-922b-ded210cf971b",
    title: "Electrician",
    description:
      "Ea et ex ea velit laboriosam aliquid. Maxime possimus maiores sed nihil non.",
    company: "Rogahn-Schultz",
    location: "Bogo, Cambodia",
    salary_from: 54097,
    salary_to: 94118,
    employment_type: "Temporary Developer",
    application_deadline: "Mon, 11/13/1995",
    qualifications:
      '["2 years of Git experience","3 years in Node.js","Skilled in GraphQL","2 years in Vue.js"]',
    contact: "569-135-726",
    job_category: "Full-stack Developer",
    is_remote_work: 0,
    number_of_opening: 2,
    created_at: "Sun, 10/15/2023",
    updated_at: "Sun, 10/15/2023",
    image: "../assets/office.avif",
  },
];
